//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dkv_baikiemtragiuaky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string MASV { get; set; }
        public string HOSV { get; set; }
        public string TENSV { get; set; }
        public string PHAI { get; set; }
        public System.DateTime NS { get; set; }
        public string MAKHOA { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
